module.exports = {
    PROJECT_ID: 'DEMApp',
    LANGUAGE_CODE: 'en-US',
    ENCODING: 'AUDIO_ENCODING_LINEAR_16',
    SAMPLE_RATE_HERZ: 16000,
    SINGLE_UTTERANCE: false,
    BASE_LANG: 'en-US',
    SSML_GENDER: 'NEUTRAL',
    SPEECH_ENCODING: 'LINEAR16',
    RECORDING_DIR: 'Recordings',
    RT_CHUNKS_DIR: 'RT_Chunks',
    RT_COMBINED_CHUNKS: 'RT_Combined_Chunks'
}